import type { Post, User, Message, Notification, Story, Event, Comment, FriendRequest } from "@/types"

// Mock Users
export const users: User[] = [
  {
    id: "1",
    name: "Phuong Tay ",
    avatar: "/avatar.png",
    coverPhoto: "/dancer-bg.gif",
    email: "an.nguyen@example.com",
  
    bio: "Nhiếp ảnh gia, yêu thích du lịch và khám phá ẩm thực mới.",
    location: "Hà Nội, Việt Nam",
    workplace: "Công ty ABC",
    education: "Đại học Bách Khoa Hà Nội",
    followers: 1245,
    following: 356,
     stats: {
            profileViews: 1000,
            totalLikes: 100,
            totalComments: 50,
            postViews: 2000,
            friendsCount: 100,
        },
    photos: 89,
    isOnline: true,
    interests: ["Nhiếp ảnh", "Du lịch", "Ẩm thực", "Công nghệ"],
    mutualFriends: 15,
  },
  {
    id: "2",
    name: "Trần Thị Bình",
    username: "binhtran",
    email: "binh.tran@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=TTB",
    coverPhoto: "/placeholder.svg?height=400&width=1200&text=Cover+Photo",
    bio: "Giáo viên tiếng Anh, đam mê đọc sách và yoga.",
    location: "Hồ Chí Minh, Việt Nam",
    workplace: "Trường THPT XYZ",
    education: "Đại học Sư phạm TP.HCM",
    followers: 876,
    following: 234,
    stats: {
      profileViews: 800,
      totalLikes: 80,
      totalComments: 40,
      postViews: 1500,
      friendsCount: 80,
    },
    photos: 45,
    isOnline: true,
    interests: ["Sách", "Yoga", "Giáo dục", "Ngoại ngữ"],
    mutualFriends: 8,
  },
  {
    id: "3",
    name: "Lê Minh Cường",
    username: "cuongle",
    email: "cuong.le@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=LMC",
    coverPhoto: "/placeholder.svg?height=400&width=1200&text=Cover+Photo",
    bio: "Kỹ sư phần mềm, chuyên gia AI và machine learning.",
    location: "Đà Nẵng, Việt Nam",
    workplace: "Tech Solutions Inc.",
    education: "Đại học Công nghệ",
    followers: 2345,
    following: 178,
    stats: {
      profileViews: 1200,
      totalLikes: 150,
      totalComments: 60,
      postViews: 2500,
      friendsCount: 120,
    },
    photos: 32,
    isOnline: true,
    interests: ["Công nghệ", "AI", "Lập trình", "Đọc sách"],
    mutualFriends: 5,
  },
  {
    id: "4",
    name: "Phạm Thị Dung",
    username: "dungpham",
    email: "dung.pham@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=PTD",
    coverPhoto: "/placeholder.svg?height=400&width=1200&text=Cover+Photo",
    bio: "Chuyên viên marketing, yêu thích âm nhạc và nấu ăn.",
    location: "Hải Phòng, Việt Nam",
    workplace: "Creative Marketing Agency",
    education: "Đại học Kinh tế Quốc dân",
    followers: 987,
    following: 432,
    stats: {
      profileViews: 900,
      totalLikes: 90,
      totalComments: 45,
      postViews: 1800,
      friendsCount: 90,
    },
    photos: 67,
    isOnline: false,
    interests: ["Marketing", "Âm nhạc", "Nấu ăn", "Thời trang"],
    mutualFriends: 12,
  },
  {
    id: "5",
    name: "Hoàng Văn Em",
    username: "emhoang",
    email: "em.hoang@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=HVE",
    coverPhoto: "/placeholder.svg?height=400&width=1200&text=Cover+Photo",
    bio: "Kiến trúc sư, đam mê thiết kế và nghệ thuật.",
    location: "Huế, Việt Nam",
    workplace: "Công ty Kiến trúc Việt",
    education: "Đại học Kiến trúc Hà Nội",
    followers: 654,
    following: 321,
    stats: {
      profileViews: 700,
      totalLikes: 70,
      totalComments: 35,
      postViews: 1200,
      friendsCount: 70,
    },
    photos: 98,
    isOnline: false,
    interests: ["Kiến trúc", "Nghệ thuật", "Thiết kế", "Du lịch"],
    mutualFriends: 3,
  },
  {
    id: "6",
    name: "Đỗ Thị Lan",
    username: "lando",
    email: "lan.do@example.com",
    avatar: "/placeholder.svg?height=40&width=40&text=DTL",
    coverPhoto: "/placeholder.svg?height=400&width=1200&text=Cover+Photo",
    bio: "Bác sĩ nhi khoa, yêu thích âm nhạc cổ điển và chơi piano.",
    location: "Cần Thơ, Việt Nam",
    workplace: "Bệnh viện Nhi Đồng",
    education: "Đại học Y Dược TP.HCM",
    followers: 1432,
    following: 267,
    stats: {
      profileViews: 1100,
      totalLikes: 110,
      totalComments: 55,
      postViews: 2100,
      friendsCount: 110,
    },
    photos: 54,
    isOnline: false,
    interests: ["Y học", "Âm nhạc cổ điển", "Piano", "Đọc sách"],
    mutualFriends: 8,
  },
]

// Current user (for demo purposes)
export const currentUser: User = users[0] // Sử dụng user đầu tiên làm current user

// Mock Friend Requests
export const friendRequests: FriendRequest[] = [
  {
    id: "1",
    senderId: "5",
    sender: users[4],
    receiverId: "1",
    receiver: currentUser,
    status: "pending" as const,
    createdAt: "2024-06-10T09:00:00Z",
  },
  {
    id: "2",
    senderId: "4",
    sender: users[3],
    receiverId: "1",
    receiver: currentUser,
    status: "pending" as const,
    createdAt: "2024-06-10T08:30:00Z",
  },
  {
    id: "3",
    senderId: "6",
    sender: users[5],
    receiverId: "1",
    receiver: currentUser,
    status: "pending" as const,
    createdAt: "2024-06-09T14:45:00Z",
  },
]

// Mock Conversations
export const conversations = [
  {
    id: "1",
    participants: [currentUser, users[1]],
    lastMessage: {
      id: "1",
      senderId: "2",
      sender: users[1],
      receiverId: "1",
      receiver: currentUser,
      content: "Chào bạn! Dự án mới thế nào rồi?",
      type: "text",
      createdAt: "2024-06-10T16:30:00Z",
      isRead: false,
    },
    updatedAt: "2024-06-10T16:30:00Z",
  },
  {
    id: "2",
    participants: [currentUser, users[2]],
    lastMessage: {
      id: "2",
      senderId: "1",
      sender: currentUser,
      receiverId: "3",
      receiver: users[2],
      content: "Ảnh sunset đẹp quá!",
      type: "text",
      createdAt: "2024-06-10T18:45:00Z",
      isRead: true,
    },
    updatedAt: "2024-06-10T18:45:00Z",
  },
  {
    id: "3",
    participants: [currentUser, users[3]],
    lastMessage: {
      id: "3",
      senderId: "4",
      sender: users[3],
      receiverId: "1",
      receiver: currentUser,
      content: "Anh check giúp em bản thiết kế UI với ạ",
      type: "text",
      createdAt: "2024-06-09T11:20:00Z",
      isRead: true,
    },
    updatedAt: "2024-06-09T11:20:00Z",
  },
]

// Mock Posts
export const posts: Post[] = [
  {
    id: "1",
    content:
      "Vừa khám phá một quán cà phê mới tuyệt đẹp ở Hà Nội. View nhìn ra hồ, không gian yên tĩnh và cà phê thì ngon tuyệt. Ai ở gần đây thì ghé qua nhé!",
    images: ["/placeholder.svg?height=400&width=600&text=Cafe+View"],
    author: users[0],
    createdAt: "2024-06-10T08:30:00Z",
    likes: 42,
    comments: 8,
    shares: 3,
    liked: false,
    saved: false,
    topics: ["#cafe", "#hanoi", "#relax"],
  },
  {
    id: "2",
    content:
      "Mình vừa hoàn thành khóa học React Advanced. Rất nhiều kiến thức hay và thực tế. Ai quan tâm về React thì có thể inbox mình để chia sẻ tài liệu nhé!",
    author: users[2],
    createdAt: "2024-06-09T15:45:00Z",
    likes: 78,
    comments: 23,
    shares: 12,
    liked: true,
    saved: true,
    topics: ["#ReactJS", "#programming", "#webdev"],
  },
  {
    id: "3",
    content:
      "Cuối tuần vừa rồi mình đã có chuyến du lịch tuyệt vời đến Đà Lạt. Thời tiết mát mẻ, phong cảnh tuyệt đẹp. Đây là một số hình ảnh mình chụp được:",
    images: [
      "/placeholder.svg?height=400&width=600&text=Dalat+1",
      "/placeholder.svg?height=400&width=600&text=Dalat+2",
      "/placeholder.svg?height=400&width=600&text=Dalat+3",
    ],
    author: users[1],
    createdAt: "2024-06-08T10:15:00Z",
    likes: 156,
    comments: 32,
    shares: 18,
    liked: false,
    saved: true,
    topics: ["#DuLich", "#Dalat", "#weekend"],
  },
  {
    id: "4",
    content:
      "Vừa thử làm món bánh mì Việt Nam fusion với phô mai và thịt xông khói. Kết quả là cực kỳ ngon! Ai muốn công thức thì comment nhé.",
    images: ["/placeholder.svg?height=400&width=600&text=Banh+Mi+Fusion"],
    author: users[3],
    createdAt: "2024-06-07T18:20:00Z",
    likes: 89,
    comments: 45,
    shares: 7,
    liked: true,
    saved: false,
    topics: ["#AmThuc", "#cooking", "#BanhMi"],
  },
  {
    id: "5",
    content:
      "Mình vừa hoàn thành dự án thiết kế nội thất cho một căn hộ 70m2. Phong cách tối giản nhưng vẫn đảm bảo đầy đủ công năng. Mọi người xem qua và góp ý nhé!",
    images: [
      "/placeholder.svg?height=400&width=600&text=Interior+Design+1",
      "/placeholder.svg?height=400&width=600&text=Interior+Design+2",
    ],
    author: users[4],
    createdAt: "2024-06-06T14:10:00Z",
    likes: 112,
    comments: 28,
    shares: 15,
    liked: false,
    saved: false,
    topics: ["#InteriorDesign", "#minimalist", "#homedecor"],
  },
  {
    id: "6",
    content: "Hôm nay mình đã chụp được một số hình ảnh đẹp về hoàng hôn ở Hồ Tây. Ánh sáng thật tuyệt vời!",
    images: ["/placeholder.svg?height=400&width=600&text=Sunset+at+West+Lake"],
    author: users[0],
    createdAt: "2024-06-05T17:30:00Z",
    likes: 67,
    comments: 12,
    shares: 5,
    liked: true,
    saved: true,
    topics: ["#Photography", "#sunset", "#HoTay"],
  },
  {
    id: "7",
    content:
      "Vừa hoàn thành buổi tập HIIT 30 phút. Mệt nhưng cảm thấy thật tuyệt! Ai đang theo đuổi lối sống lành mạnh thì hãy thử nhé.",
    author: users[5],
    createdAt: "2024-06-04T07:45:00Z",
    likes: 45,
    comments: 8,
    shares: 2,
    liked: false,
    saved: false,
    topics: ["#Fitness", "#HIIT", "#healthylifestyle"],
  },
  {
    id: "8",
    content:
      "Mình vừa đọc xong cuốn sách 'Atomic Habits'. Thật sự là một cuốn sách tuyệt vời về việc xây dựng thói quen. Khuyên mọi người nên đọc!",
    images: ["/placeholder.svg?height=400&width=600&text=Atomic+Habits+Book"],
    author: users[1],
    createdAt: "2024-06-03T21:15:00Z",
    likes: 93,
    comments: 27,
    shares: 14,
    liked: true,
    saved: true,
    topics: ["#reading", "#AtomicHabits", "#selfimprovement"],
  },
  {
    id: "9",
    content:
      "Vừa tham gia workshop về AI và Machine Learning. Rất nhiều kiến thức mới và hữu ích. Tương lai của công nghệ thật thú vị!",
    author: users[2],
    createdAt: "2024-06-02T13:40:00Z",
    likes: 124,
    comments: 31,
    shares: 19,
    liked: false,
    saved: true,
    topics: ["#AI", "#MachineLearning", "#technology"],
  },
  {
    id: "10",
    content:
      "Cuối tuần này mình sẽ tổ chức một buổi offline giao lưu về nhiếp ảnh tại Hà Nội. Ai quan tâm thì đăng ký tham gia nhé!",
    images: ["/placeholder.svg?height=400&width=600&text=Photography+Meetup"],
    author: users[0],
    createdAt: "2024-06-01T09:25:00Z",
    likes: 56,
    comments: 42,
    shares: 8,
    liked: true,
    saved: false,
    topics: ["#Photography", "#meetup", "#Hanoi"],
  },
]

// Mock trending topics
export const trendingTopics = [
  { id: "1", name: "#ReactJS", count: 12500, change: "+15%", category: "Công nghệ", rank: 1 },
  { id: "2", name: "#DuLich", count: 8200, change: "+23%", category: "Du lịch", rank: 2 },
  { id: "3", name: "#AmThuc", count: 6800, change: "+8%", category: "Ẩm thực", rank: 3 },
  { id: "4", name: "#Photography", count: 15100, change: "+12%", category: "Nghệ thuật", rank: 4 },
  { id: "5", name: "#Fitness", count: 9300, change: "+18%", category: "Sức khỏe", rank: 5 },
  { id: "6", name: "#TechVietnam", count: 5600, change: "+21%", category: "Công nghệ", rank: 6 },
  { id: "7", name: "#DigitalTransformation", count: 4300, change: "+5%", category: "Công nghệ", rank: 7 },
]

// Mock trending posts
export const trendingPosts = [
  {
    id: "1",
    content:
      "Trí tuệ nhân tạo đang thay đổi cách chúng ta làm việc và sống. Các công nghệ mới nhất như GPT-4 và DALL-E 3 đang mở ra những khả năng chưa từng có. Bạn nghĩ gì về tương lai của AI?",
    user: users[0],
    likes: 1250,
    comments: 342,
    shares: 189,
    createdAt: "2024-06-08T10:30:00Z",
    topics: ["#AI", "#Technology", "#Future"],
  },
  {
    id: "2",
    content:
      "Việt Nam đang trở thành điểm đến hàng đầu cho các nhà đầu tư công nghệ. Với lực lượng lao động trẻ và có kỹ năng, chúng ta đang chứng kiến sự bùng nổ của các startup công nghệ trong nước.",
    user: users[1],
    likes: 980,
    comments: 215,
    shares: 145,
    createdAt: "2024-06-08T09:15:00Z",
    topics: ["#TechVietnam", "#Startup", "#Investment"],
  },
  {
    id: "3",
    content:
      "Biến đổi khí hậu là thách thức lớn nhất của thế hệ chúng ta. Mỗi người cần hành động ngay bây giờ để bảo vệ hành tinh. Hãy chia sẻ những hành động nhỏ bạn đang làm để giảm thiểu tác động môi trường!",
    user: users[2],
    likes: 875,
    comments: 198,
    shares: 256,
    createdAt: "2024-06-08T08:45:00Z",
    topics: ["#ClimateAction", "#Sustainability", "#Environment"],
    image: "/placeholder.svg?height=300&width=600&text=Climate+Action",
  },
]

// Mock trending news
export const trendingNews = [
  {
    id: "1",
    title: "Việt Nam phát triển thành công vaccine COVID-19 thế hệ mới",
    excerpt:
      "Các nhà khoa học Việt Nam vừa công bố thành công trong việc phát triển vaccine COVID-19 thế hệ mới với hiệu quả cao hơn và ít tác dụng phụ hơn.",
    source: "VnExpress",
    publishedAt: "2024-06-08T07:30:00Z",
    image: "/placeholder.svg?height=200&width=400&text=Vaccine+News",
    readTime: "5 phút đọc",
    category: "Sức khỏe",
  },
  {
    id: "2",
    title: "Thị trường bất động sản phục hồi mạnh mẽ trong quý 2/2024",
    excerpt:
      "Sau giai đoạn trầm lắng, thị trường bất động sản Việt Nam đang cho thấy dấu hiệu phục hồi rõ rệt với lượng giao dịch tăng 25% so với cùng kỳ năm ngoái.",
    source: "Báo Đầu tư",
    publishedAt: "2024-06-08T06:45:00Z",
    image: "/placeholder.svg?height=200&width=400&text=Real+Estate",
    readTime: "7 phút đọc",
    category: "Kinh tế",
  },
  {
    id: "3",
    title: "Đội tuyển Việt Nam chuẩn bị cho vòng loại World Cup 2026",
    excerpt:
      "HLV trưởng đội tuyển Việt Nam vừa công bố danh sách 30 cầu thủ được triệu tập cho đợt tập trung chuẩn bị cho các trận đấu vòng loại World Cup 2026.",
    source: "Bóng đá Plus",
    publishedAt: "2024-06-08T08:15:00Z",
    image: "/placeholder.svg?height=200&width=400&text=Vietnam+Football+Team",
    readTime: "4 phút đọc",
    category: "Thể thao",
  },
]

// Mock Messages
export const messages: Message[] = [
  {
    id: "1",
    senderId: "2",
    receiverId: "1",
    content: "Chào bạn, cuối tuần này bạn có rảnh không?",
    timestamp: "2024-06-10T09:30:00Z",
    read: true,
  },
  {
    id: "2",
    senderId: "1",
    receiverId: "2",
    content: "Chào bạn! Mình rảnh vào chiều thứ 7, bạn có kế hoạch gì không?",
    timestamp: "2024-06-10T09:35:00Z",
    read: true,
  },
  {
    id: "3",
    senderId: "2",
    receiverId: "1",
    content: "Mình đang nghĩ đến việc đi cafe và trò chuyện về dự án mới. Bạn thấy sao?",
    timestamp: "2024-06-10T09:40:00Z",
    read: true,
  },
  {
    id: "4",
    senderId: "3",
    receiverId: "1",
    content: "Anh ơi, anh có thể gửi cho em tài liệu về React hooks được không ạ?",
    timestamp: "2024-06-09T14:20:00Z",
    read: false,
  },
  {
    id: "5",
    senderId: "1",
    receiverId: "3",
    content: "Được chứ, để anh gửi cho em ngay nhé!",
    timestamp: "2024-06-09T14:25:00Z",
    read: true,
  },
  {
    id: "6",
    senderId: "4",
    receiverId: "1",
    content: "Chào anh, em đã hoàn thành bản thiết kế UI cho dự án. Anh check giúp em nhé!",
    timestamp: "2024-06-08T11:10:00Z",
    read: true,
  },
]

// Mock Notifications
export const notifications: Notification[] = [
  {
    id: "1",
    userId: "1",
    type: "like",
    content: "đã thích bài viết của bạn",
    actorId: "2",
    targetId: "1",
    read: false,
    createdAt: "2024-06-10T10:15:00Z",
  },
  {
    id: "2",
    userId: "1",
    type: "comment",
    content: "đã bình luận về bài viết của bạn",
    actorId: "3",
    targetId: "1",
    read: false,
    createdAt: "2024-06-10T09:45:00Z",
  },
  {
    id: "3",
    userId: "1",
    type: "friend_request",
    content: "đã gửi cho bạn lời mời kết bạn",
    actorId: "4",
    targetId: null,
    read: true,
    createdAt: "2024-06-09T16:30:00Z",
  },
  {
    id: "4",
    userId: "1",
    type: "share",
    content: "đã chia sẻ bài viết của bạn",
    actorId: "5",
    targetId: "3",
    read: true,
    createdAt: "2024-06-09T14:20:00Z",
  },
  {
    id: "5",
    userId: "1",
    type: "mention",
    content: "đã nhắc đến bạn trong một bình luận",
    actorId: "2",
    targetId: "5",
    read: false,
    createdAt: "2024-06-08T11:05:00Z",
  },
]

// Mock Stories
export const stories: Story[] = [
  {
    id: "1",
    userId: "1",
    user: users[0],
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    createdAt: "2024-06-10T08:00:00Z",
    expiresAt: "2024-06-11T08:00:00Z",
    views: 45,
    caption: "Buổi sáng tuyệt vời ở Hồ Tây",
  },
  {
    id: "2",
    userId: "2",
    user: users[1],
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    createdAt: "2024-06-10T09:30:00Z",
    expiresAt: "2024-06-11T09:30:00Z",
    views: 78,
    caption: "Coffee time ☕",
  },
  {
    id: "3",
    userId: "3",
    user: users[2],
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
    createdAt: "2024-06-10T10:15:00Z",
    expiresAt: "2024-06-11T10:15:00Z",
    views: 120,
    caption: "Coding day!",
  },
  {
    id: "4",
    userId: "4",
    user: users[3],
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
    createdAt: "2024-06-10T11:45:00Z",
    expiresAt: "2024-06-11T11:45:00Z",
    views: 67,
    caption: "Lunch with colleagues",
  },
  {
    id: "5",
    userId: "5",
    user: users[4],
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    createdAt: "2024-06-10T13:20:00Z",
    expiresAt: "2024-06-11T13:20:00Z",
    views: 92,
    caption: "New design project",
  },
]

// Mock Events
export const events: Event[] = [
  {
    id: "1",
    title: "Workshop: Thiết kế UI/UX cho người mới bắt đầu",
    description:
      "Workshop chia sẻ kiến thức và kỹ năng cơ bản về thiết kế UI/UX cho người mới bắt đầu. Bạn sẽ được học cách sử dụng các công cụ thiết kế phổ biến và nguyên tắc thiết kế cơ bản.",
    location: "Toong Coworking Space, 8 Tràng Thi, Hà Nội",
    startDate: "2024-06-15T09:00:00Z",
    endDate: "2024-06-15T16:00:00Z",
    image: "/placeholder.svg?height=300&width=600&text=UI/UX+Workshop",
    organizer: users[0],
    attendees: 45,
    interested: 120,
    price: "200.000 VNĐ",
    category: "Technology",
  },
  {
    id: "2",
    title: "Triển lãm Nhiếp ảnh Việt Nam 2024",
    description:
      "Triển lãm giới thiệu các tác phẩm nhiếp ảnh xuất sắc của các nhiếp ảnh gia Việt Nam. Chủ đề năm nay là 'Việt Nam - Đất nước và Con người'.",
    location: "Bảo tàng Mỹ thuật Việt Nam, 66 Nguyễn Thái Học, Hà Nội",
    startDate: "2024-06-20T08:00:00Z",
    endDate: "2024-06-25T17:00:00Z",
    image: "/placeholder.svg?height=300&width=600&text=Photography+Exhibition",
    organizer: users[4],
    attendees: 230,
    interested: 560,
    price: "Miễn phí",
    category: "Art",
  },
  {
    id: "3",
    title: "Tech Meetup: AI và Machine Learning",
    description:
      "Gặp gỡ và chia sẻ kiến thức về AI và Machine Learning. Sự kiện có sự tham gia của các chuyên gia hàng đầu trong lĩnh vực.",
    location: "Dreamplex Coworking Space, 195 Điện Biên Phủ, Quận 1, TP.HCM",
    startDate: "2024-06-18T18:30:00Z",
    endDate: "2024-06-18T21:00:00Z",
    image: "/placeholder.svg?height=300&width=600&text=AI+Meetup",
    organizer: users[2],
    attendees: 85,
    interested: 210,
    price: "Miễn phí",
    category: "Technology",
  },
  {
    id: "4",
    title: "Workshop Nấu ăn: Ẩm thực Ý",
    description: "Học cách nấu các món ăn Ý truyền thống như pasta, pizza và tiramisu từ đầu bếp chuyên nghiệp.",
    location: "Culinary Arts Center, 24 Thảo Điền, Quận 2, TP.HCM",
    startDate: "2024-06-22T14:00:00Z",
    endDate: "2024-06-22T17:00:00Z",
    image: "/placeholder.svg?height=300&width=600&text=Italian+Cooking",
    organizer: users[3],
    attendees: 25,
    interested: 78,
    price: "350.000 VNĐ",
    category: "Food",
  },
  {
    id: "5",
    title: "Yoga ngoài trời tại Công viên Thống Nhất",
    description: "Buổi tập yoga ngoài trời miễn phí cho mọi người. Hãy mang theo thảm yoga và nước uống của bạn.",
    location: "Công viên Thống Nhất, Hà Nội",
    startDate: "2024-06-16T06:30:00Z",
    endDate: "2024-06-16T07:30:00Z",
    image: "/placeholder.svg?height=300&width=600&text=Outdoor+Yoga",
    organizer: users[1],
    attendees: 40,
    interested: 95,
    price: "Miễn phí",
    category: "Health",
  },
]

// Mock Comments
export const comments: Comment[] = [
  {
    id: "1",
    postId: "1",
    userId: "2",
    content: "Quán này ở đâu vậy bạn? Nhìn đẹp quá!",
    createdAt: "2024-06-10T09:00:00Z",
    likes: 5,
  },
  {
    id: "2",
    postId: "1",
    userId: "3",
    content: "Mình đã từng đến đây, cà phê rất ngon và không gian rất thoải mái.",
    createdAt: "2024-06-10T09:15:00Z",
    likes: 3,
  },
  {
    id: "3",
    postId: "1",
    userId: "1",
    content: "Quán ở ngõ 35 Trần Thái Tông nhé, gần hồ Ngọc Khánh.",
    createdAt: "2024-06-10T09:30:00Z",
    likes: 2,
    parentId: "1",
  },
  {
    id: "4",
    postId: "2",
    userId: "4",
    content: "Bạn có thể chia sẻ tài liệu cho mình được không? Mình cũng đang học React.",
    createdAt: "2024-06-09T16:00:00Z",
    likes: 1,
  },
  {
    id: "5",
    postId: "2",
    userId: "2",
    content: "Khóa học này ở đâu vậy bạn?",
    createdAt: "2024-06-09T16:30:00Z",
    likes: 0,
  },
  {
    id: "6",
    postId: "3",
    userId: "5",
    content: "Đà Lạt đẹp quá! Bạn ở đó mấy ngày vậy?",
    createdAt: "2024-06-08T11:00:00Z",
    likes: 4,
  },
  {
    id: "7",
    postId: "3",
    userId: "1",
    content: "Mình ở đó 3 ngày 2 đêm. Thời tiết rất mát mẻ.",
    createdAt: "2024-06-08T11:30:00Z",
    likes: 2,
    parentId: "6",
  },
]

// Mock Friend Suggestions
export const friendSuggestions = [
  {
    id: "11",
    name: "Đỗ Thị Lan",
    avatar: "/placeholder.svg?height=40&width=40&text=DTL",
    mutualFriends: 8,
    workplace: "Công ty ABC",
    isOnline: true,
  },
  {
    id: "12",
    name: "Bùi Văn Nam",
    avatar: "/placeholder.svg?height=40&width=40&text=BVN",
    mutualFriends: 5,
    education: "Đại học Bách Khoa",
    isOnline: false,
  },
  {
    id: "13",
    name: "Lý Thị Hoa",
    avatar: "/placeholder.svg?height=40&width=40&text=LTH",
    mutualFriends: 12,
    location: "Hà Nội",
    isOnline: true,
  },
]

// Backward compatibility exports
export const mockPosts = posts
export const mockUsers = users
export const mockConversations = conversations
export const mockNotifications = notifications




export const profileData = {
  ...currentUser,
  coverPhoto: "/placeholder.svg?height=300&width=800&text=Cover+Photo",
  birthday: "1995-03-15",
  gender: "Nam",
  relationship: "Độc thân",
  hometown: "Hà Nội, Việt Nam",
  languages: ["Tiếng Việt", "English", "日本語"],
  interests: ["Công nghệ", "Du lịch", "Nhiếp ảnh", "Âm nhạc", "Thể thao"],
  education: [
    {
      school: "Đại học Bách Khoa Hà Nội",
      degree: "Kỹ sư Công nghệ Thông tin",
      year: "2013-2017",
      description: "Chuyên ngành Phát triển phần mềm",
    },
    {
      school: "Trường THPT Chu Văn An",
      degree: "Tốt nghiệp THPT",
      year: "2010-2013",
      description: "Lớp chuyên Toán",
    },
  ],
  workExperience: [
    {
      company: "Tech Solutions Vietnam",
      position: "Senior Full-stack Developer",
      period: "2020 - Hiện tại",
      description: "Phát triển và duy trì các ứng dụng web quy mô lớn sử dụng React, Node.js và MongoDB.",
    },
    {
      company: "StartupXYZ",
      position: "Frontend Developer",
      period: "2018 - 2020",
      description: "Xây dựng giao diện người dùng cho ứng dụng mobile và web.",
    },
  ],
  achievements: [
    {
      title: "Nhân viên xuất sắc năm 2023",
      organization: "Tech Solutions Vietnam",
      date: "2023-12-01",
      description: "Được công nhận vì đóng góp xuất sắc trong dự án phát triển hệ thống ERP.",
    },
    {
      title: "Giải nhất Hackathon 2022",
      organization: "Vietnam Tech Community",
      date: "2022-08-15",
      description: "Đội phát triển ứng dụng AI cho giáo dục.",
    },
  ],
  skills: [
    { name: "React", level: 95 },
    { name: "Node.js", level: 90 },
    { name: "TypeScript", level: 88 },
    { name: "Python", level: 85 },
    { name: "MongoDB", level: 82 },
    { name: "AWS", level: 78 },
  ],
  socialLinks: [
    { platform: "GitHub", url: "https://github.com/nguyenvanan", icon: "🐙" },
    { platform: "LinkedIn", url: "https://linkedin.com/in/nguyenvanan", icon: "💼" },
    { platform: "Twitter", url: "https://twitter.com/nguyenvanan", icon: "🐦" },
  ],
  stats: {
    profileViews: 1250,
    postViews: 15600,
    totalLikes: 3420,
    totalComments: 890,
    friendsCount: 156,
  },
}

// Mẫu ảnh cho gallery
 export const userPhotos = [
  {
    id: "1",
    url: "/placeholder.svg?height=300&width=300&text=Photo+1",
    caption: "Chuyến du lịch Hạ Long",
    date: "2024-05-20T15:30:00Z",
    likes: 45,
    comments: 12,
  },
  {
    id: "2",
    url: "/placeholder.svg?height=300&width=300&text=Photo+2",
    caption: "Workshop công nghệ",
    date: "2024-04-15T10:00:00Z",
    likes: 32,
    comments: 8,
  },
  {
    id: "3",
    url: "/placeholder.svg?height=300&width=300&text=Photo+3",
    caption: "Sinh nhật lần thứ 29",
    date: "2024-03-15T18:45:00Z",
    likes: 78,
    comments: 25,
  },
  {
    id: "4",
    url: "/placeholder.svg?height=300&width=300&text=Photo+4",
    caption: "Hackathon 2024",
    date: "2024-02-10T14:20:00Z",
    likes: 56,
    comments: 15,
  },
  {
    id: "5",
    url: "/placeholder.svg?height=300&width=300&text=Photo+5",
    caption: "Team building",
    date: "2024-01-25T11:30:00Z",
    likes: 34,
    comments: 9,
  },
  {
    id: "6",
    url: "/placeholder.svg?height=300&width=300&text=Photo+6",
    caption: "Dự án mới",
    date: "2024-01-10T16:15:00Z",
    likes: 67,
    comments: 18,
  },
]